FROM nginx
COPY nginx.conf /etc/nginx/nginx.conf
COPY fullchain.pem /etc/letsencrypt/live/nhs0912-subway-infra.kro.kr/fullchain.pem
COPY privkey.pem /etc/letsencrypt/live/nhs0912-subway-infra.kro.kr/privkey.pem
