#!/bin/bash

## 변수 설정

txtrst='\033[1;37m' # White
txtred='\033[1;31m' # Red
txtylw='\033[1;33m' # Yellow
txtpur='\033[1;35m' # Purple
txtgrn='\033[1;32m' # Green
txtgra='\033[1;30m' # Gray

EXECUTION_PATH=$(pwd)
SHELL_SCRIPT_PATH=$(dirname $0)
BRANCH=$1
PROFILE=$2

## 조건 설정
if [[ $# -ne 2 ]]
then
    echo -e "${txtylw}=======================================${txtrst}"
    echo -e "${txtgrn}  << 스크립트 🧐 >>${txtrst}"
    echo -e ""
    echo -e "${txtgrn} $0 브랜치이름 ${txtred}{ prod | dev }"
    echo -e "${txtylw}=======================================${txtrst}"
    exit
fi

echo -e "${txtylw}=======================================${txtrst}"
echo -e "${txtgrn}  << 스크립트 🧐 >>${txtrst}"
echo -e "${txtylw}=======================================${txtrst}"

function check_df() {
  git fetch
  master=$(git rev-parse $BRANCH)
  remote=$(git rev-parse origin/$BRANCH)

  if [[ $master == $remote ]]; then
    echo -e "[$(date)] Nothing to do!!! 😫"
    exit 0
  fi
}
check_df;

## 저장소 pull
function pull() {
  echo -e ""
  echo -e ">> Pull Request 🏃♂️ "
  git pull origin $BRANCH
  git submodule init
  git submodule update
}
pull;

## gradle build
$SHELL_SCRIPT_PATH/gradlew clean build

## 프로세스 pid를 찾는 명령어
PID=`pgrep -f $SHELL_SCRIPT_PATH/build/libs/*.jar`

## 프로세스를 종료하는 명령어
if [[ -n "$PID" ]]; then
  kill -9 $PID
fi

## 프로세스를 실행!
JARFILE=`find $SHELL_SCRIPT_PATH/build/libs/* -name "*jar"`
nohub java -jar -Dspring.profiles.active=$PROFILE $JARFILE 1> ~/subway.log 2>&1 &
