version: '3'
services:
  mysql:
    container_name: mysql-subway
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: subway
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci