spring:
  flyway:
    enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/infra-subway-deploy?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
