FROM nginx

COPY nginx.conf /etc/nginx/nginx.conf 
COPY fullchain.pem /etc/letsencrypt/live/www.find-subway.p-e.kr/fullchain.pem
COPY privkey.pem /etc/letsencrypt/live/www.find-subway.p-e.kr/privkey.pem
