version: "3.7"

services:
  app:
    image: nextstep/app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILE=prod
  nginx:
    image: nextstep/reverse-proxy
    ports:
      - "80:80"
      - "443:443"
