FROM nginx
COPY docker/nginx/nginx.conf /etc/nginx/nginx.conf
COPY docker/nginx/fullchain.pem /etc/letsencrypt/live/y2o2u2n.p-e.kr/fullchain.pem
COPY docker/nginx/privkey.pem /etc/letsencrypt/live/y2o2u2n.p-e.kr/privkey.pem
