    create table flyway_test (
       id bigint generated by default as identity,
        created_date timestamp,
        modified_date timestamp,
        name varchar(255),
        primary key (id)
    );
