INSERT INTO STATION(
    NAME
) VALUES (
    SELECT '서울역' AS NAME FROM DUAL UNION ALL
    SELECT '광명역' AS NAME FROM DUAL UNION ALL
    SELECT '대전역' AS NAME FROM DUAL UNION ALL
    SELECT '동대구역' AS NAME FROM DUAL UNION ALL
    SELECT '부산역' AS NAME FROM DUAL
)
